VERSION       = 0.1
NAME          = server
DIR           = ubuntu
user          = root

##############################################################################

include etc/rules/keys.mk
include etc/rules/docker.mk
include etc/rules/ssh.mk
