VERSION       = 0.1
DIR           = chef
NAME          = solo
user          = dev

##############################################################################

include etc/rules/keys.mk
include etc/rules/docker.mk
include etc/rules/ssh.mk
